#ifndef POSTPROCESSING_GLOBAL_H
#define POSTPROCESSING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(POSTPROCESSING_LIBRARY)
#  define POSTPROCESSING_EXPORT Q_DECL_EXPORT
#else
#  define POSTPROCESSING_EXPORT Q_DECL_IMPORT
#endif

#endif // POSTPROCESSING_GLOBAL_H
